import { lstat, readFile, readdir } from "node:fs/promises";
import { basename, join, posix, resolve, sep } from "node:path";

import { sha256 } from "../../core/digest.ts";
import { DokionError } from "../../core/errors.ts";
import type { PackageFileEvidence, PackageLimits, TarSourceEntry } from "./types.ts";

export interface SourceInventory {
  files: PackageFileEvidence[];
  entries: TarSourceEntry[];
  expandedBytes: number;
}

function mediaType(path: string): string {
  const extension = path.toLowerCase().split(".").pop();
  switch (extension) {
    case "json":
      return "application/json";
    case "md":
    case "markdown":
      return "text/markdown";
    case "txt":
    case "license":
      return "text/plain";
    case "yaml":
    case "yml":
      return "application/yaml";
    case "toml":
      return "application/toml";
    case "svg":
      return "image/svg+xml";
    case "png":
      return "image/png";
    case "jpg":
    case "jpeg":
      return "image/jpeg";
    case "webp":
      return "image/webp";
    default:
      return "application/octet-stream";
  }
}

function assertSafeRelativePath(path: string, limits: PackageLimits): void {
  const bytes = Buffer.byteLength(path, "utf8");
  if (bytes === 0 || bytes > limits.maximumPathBytes) {
    throw new DokionError("PACKAGE_SOURCE_INVALID", "Package path is empty or exceeds the USTAR path limit", {
      path,
      bytes,
      maximum: limits.maximumPathBytes
    });
  }
  if (
    path.startsWith("/") ||
    path.includes("\\") ||
    path.split("/").some((segment) => segment.length === 0 || segment === "." || segment === "..") ||
    path.includes("\0")
  ) {
    throw new DokionError("PACKAGE_SOURCE_INVALID", "Package path is not a safe relative POSIX path", { path });
  }
}

function filesystemPath(root: string, relativePath: string): string {
  return join(root, ...relativePath.split("/"));
}

export async function inventoryPackageSource(sourceDirectory: string, limits: PackageLimits): Promise<SourceInventory> {
  const sourceRoot = resolve(sourceDirectory);
  const sourceStat = await lstat(sourceRoot).catch(() => null);
  if (!sourceStat?.isDirectory() || sourceStat.isSymbolicLink()) {
    throw new DokionError("PACKAGE_SOURCE_INVALID", "Package source must be a real directory", {
      sourceDirectory
    });
  }

  const paths: string[] = [];

  async function walk(relativeDirectory: string): Promise<void> {
    const directoryPath = relativeDirectory ? filesystemPath(sourceRoot, relativeDirectory) : sourceRoot;
    const children = await readdir(directoryPath, { withFileTypes: true });
    children.sort((left, right) => Buffer.from(left.name).compare(Buffer.from(right.name)));

    for (const child of children) {
      const relativePath = relativeDirectory ? posix.join(relativeDirectory, child.name) : child.name;
      assertSafeRelativePath(relativePath, limits);
      const absolutePath = filesystemPath(sourceRoot, relativePath);
      const observed = await lstat(absolutePath);

      if (observed.isSymbolicLink()) {
        throw new DokionError("PACKAGE_SOURCE_INVALID", "Package sources cannot contain symbolic links", {
          path: relativePath
        });
      }
      if (observed.isDirectory()) {
        await walk(relativePath);
        continue;
      }
      if (!observed.isFile()) {
        throw new DokionError("PACKAGE_SOURCE_INVALID", "Package sources may contain regular files only", {
          path: relativePath,
          mode: observed.mode
        });
      }
      if (relativePath === "manifest.json") {
        throw new DokionError("PACKAGE_SOURCE_INVALID", "manifest.json is generated by Dokion and cannot be supplied", {
          path: relativePath
        });
      }
      paths.push(relativePath);
      if (paths.length > limits.maximumFiles) {
        throw new DokionError("PACKAGE_LIMIT_EXCEEDED", "Package source exceeds the maximum file count", {
          maximumFiles: limits.maximumFiles
        });
      }
    }
  }

  await walk("");
  paths.sort((left, right) => Buffer.from(left).compare(Buffer.from(right)));

  const files: PackageFileEvidence[] = [];
  const entries: TarSourceEntry[] = [];
  let expandedBytes = 0;

  for (const path of paths) {
    const absolutePath = filesystemPath(sourceRoot, path);
    const before = await lstat(absolutePath);
    const bytes = new Uint8Array(await readFile(absolutePath));
    const after = await lstat(absolutePath);

    if (!before.isFile() || !after.isFile() || before.size !== after.size || before.mtimeMs !== after.mtimeMs) {
      throw new DokionError("PACKAGE_SOURCE_INVALID", "Package source changed while it was being inventoried", {
        path
      });
    }
    if (bytes.byteLength !== before.size) {
      throw new DokionError("PACKAGE_SOURCE_INVALID", "Package source size changed while it was being read", {
        path,
        expected: before.size,
        observed: bytes.byteLength
      });
    }
    if (bytes.byteLength > limits.maximumFileBytes) {
      throw new DokionError("PACKAGE_LIMIT_EXCEEDED", "Package file exceeds the per-file byte limit", {
        path,
        bytes: bytes.byteLength,
        maximum: limits.maximumFileBytes
      });
    }

    expandedBytes += bytes.byteLength;
    if (expandedBytes > limits.maximumExpandedBytes) {
      throw new DokionError("PACKAGE_LIMIT_EXCEEDED", "Package source exceeds the expanded byte limit", {
        expandedBytes,
        maximum: limits.maximumExpandedBytes
      });
    }

    files.push({
      path,
      kind: "file",
      media_type: basename(path) === "LICENSE" ? "text/plain" : mediaType(path),
      size: bytes.byteLength,
      digest: sha256(bytes)
    });
    entries.push({ path, bytes });
  }

  return { files, entries, expandedBytes };
}
