export type DokionErrorCode =
  | "NO_ACTIVE_PLAYBOOK"
  | "INVALID_JSON"
  | "INVALID_MANIFEST"
  | "INVALID_PLAYBOOK"
  | "INVALID_STATE"
  | "INVALID_EVENT"
  | "UNPINNED_CAPABILITY"
  | "PLAYBOOK_TAINTED"
  | "WORKTREE_POLICY_UNAVAILABLE"
  | "DIRTY_WORKTREE_BLOCKED"
  | "WORKTREE_SNAPSHOT_FAILED"
  | "STATE_NOT_FOUND"
  | "GOAL_NOT_FOUND"
  | "STATE_REVISION_CONFLICT"
  | "STATE_WRITE_LOCKED"
  | "RUN_LOCKED"
  | "RUN_LOCK_STALE"
  | "INVALID_RUN_LOCK"
  | "APPROVAL_REQUIRED"
  | "COMMAND_FAILED"
  | "DEPENDENCY_UNMET"
  | "UNSUPPORTED_EXECUTION"
  | "REGISTRY_SOURCE_REQUIRED"
  | "REGISTRY_NOT_IMPLEMENTED"
  | "REGISTRY_PACKAGE_CONFIG_INVALID"
  | "REGISTRY_PACKAGE_REQUIRED_FILE_MISSING"
  | "REGISTRY_PACKAGE_PATH_INVALID"
  | "REGISTRY_PACKAGE_PATH_DUPLICATE"
  | "REGISTRY_PACKAGE_CASE_COLLISION"
  | "REGISTRY_PACKAGE_ENTRY_TYPE_UNSUPPORTED"
  | "REGISTRY_PACKAGE_FILE_TOO_LARGE"
  | "REGISTRY_PACKAGE_TOO_LARGE"
  | "REGISTRY_PACKAGE_TOO_MANY_FILES"
  | "REGISTRY_PACKAGE_COMPRESSION_UNSUPPORTED"
  | "REGISTRY_PACKAGE_ARCHIVE_INVALID"
  | "REGISTRY_PACKAGE_MANIFEST_INVALID"
  | "REGISTRY_PACKAGE_UNDECLARED_FILE"
  | "REGISTRY_PACKAGE_DECLARED_FILE_MISSING"
  | "REGISTRY_PACKAGE_DIGEST_MISMATCH"
  | "REGISTRY_PACKAGE_SIZE_MISMATCH"
  | "REGISTRY_PACKAGE_ID_MISMATCH"
  | "REGISTRY_PACKAGE_VERSION_MISMATCH"
  | "REGISTRY_PACKAGE_INCOMPATIBLE"
  | "REGISTRY_PACKAGE_OUTPUT_EXISTS"
  | "REGISTRY_PACKAGE_LIFECYCLE_SCRIPT"
  | "REGISTRY_PACKAGE_AUTHORITY_CLAIM"
  | "CLI_UNKNOWN_COMMAND"
  | "CLI_PLANNED_COMMAND"
  | "CLI_UNKNOWN_OPTION"
  | "CLI_MISSING_OPTION_VALUE"
  | "CLI_DUPLICATE_OPTION"
  | "CLI_MISSING_ARGUMENT"
  | "CLI_INVALID_ARGUMENT";

export class DokionError extends Error {
  readonly code: DokionErrorCode;
  readonly details: Readonly<Record<string, unknown>>;

  constructor(code: DokionErrorCode, message: string, details: Record<string, unknown> = {}) {
    super(message);
    this.name = "DokionError";
    this.code = code;
    this.details = Object.freeze({ ...details });
  }
}
